# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
caroline = User.create(username:'cslee95' , name: 'Caroline' , password: 'caroline1')
anna = User.create(username:'annabanana' , name: 'Anna' , password: 'anna1')
ana = User.create(username:'anaLlama' , name: 'Ana' , password: 'ana1' )
marissa = User.create(username:'MarissaFelicia', name: 'Marissa', password: 'marissa1' )
beth = User.create(username:'mcBeth' , name: 'Beth' , password: 'beth1')
jenny = User.create(username:'MamaJenny' , name: 'Jenny' , password: 'jenny1')
mike = User.create(username:'mikekimismikekimbackards' , name: 'Mike' , password: 'mike1')
iman = User.create(username:'imanji' , name: 'Iman' , password: 'iman1' )
robin = User.create(username:'hoodRobin' , name: 'Robin' , password: 'robin1')
joseph = User.create(username:'traderJoes' , name: 'Joseph' , password: 'joseph1')
jason = User.create(username:'Spacson' , name: 'Jason' , password: 'jason1')
andrew = User.create(username:'Drew' , name: 'Andrew' , password: 'andrew1')
hillary = User.create(username:'Hillaryous' , name: 'Hillary' , password: 'hillary1')
lane = User.create(username:'getinyourLane' , name: 'Lane' , password: 'lane1')
ann = User.create(username:'h-ann-d' , name: 'Ann' , password: 'ann1')

e1 = Emotion.create(mood:'Angry')
e2 = Emotion.create(mood:'Stressed')
e3 = Emotion.create(mood:'Anxious')
e4 = Emotion.create(mood:'Exhausted')
e5 = Emotion.create(mood:'Burnt out')
e6 = Emotion.create(mood:'Okay')
e7 = Emotion.create(mood:'Content')
e8 = Emotion.create(mood:'Excited')
e9 = Emotion.create(mood:'Happy')
e10 = Emotion.create(mood:'Best Day Ever')


t1 = Timesheet.create(user_id: caroline.id, date:'2019-01-01', text:'Finished alot of work!', food:3, water:3, hours_of_sleep:6, bowel_movement:0, friends:0, family:4 )
t2 = Timesheet.create(user_id: caroline.id, date:'2019-01-02', text:'Started my period.', food:2, water:4, hours_of_sleep:7, bowel_movement:1, friends:0, family:3)
t3 = Timesheet.create(user_id: caroline.id, date:'2019-01-03', text:'Did not get to finish the amount of work I wanted to get done.', food:3, water:4, hours_of_sleep:6, bowel_movement:1, friends:0, family:1)
t4 = Timesheet.create(user_id: caroline.id, date:'2019-01-05', text:'Work finished.', food:1, water:5, hours_of_sleep:5, bowel_movement:2, friends:0, family:1)
t5 = Timesheet.create(user_id: caroline.id, date:'2019-01-04', text:'Just worked all day.',food:2, water:5, hours_of_sleep:6, bowel_movement:1, friends:0, family:1)
t6 = Timesheet.create(user_id: caroline.id, date:'2019-01-06', text:'Didnt go to church, was with friends.',food:3, water:6, hours_of_sleep:7, bowel_movement:0, friends:2, family:2)
t7 = Timesheet.create(user_id: caroline.id, date:'2019-01-07', text:'Was at school the whole day.',food:0, water:1, hours_of_sleep:5, bowel_movement:1, friends:0, family:1)
t8 = Timesheet.create(user_id: caroline.id, date:'2019-01-08', text:'Another day at school.',food:1, water:2, hours_of_sleep:4, bowel_movement:3, friends:0, family:0)
t9 = Timesheet.create(user_id: caroline.id, date:'2019-01-09', text:'Another day at school.',food:0, water:2, hours_of_sleep:3, bowel_movement:1, friends:0, family:0)
t10 = Timesheet.create(user_id: caroline.id, date:'2019-01-10', text:'Another day at school.',food:1, water:2, hours_of_sleep:4, bowel_movement:3, friends:0, family:0)
t11 = Timesheet.create(user_id: caroline.id, date:'2019-01-11', text:'Its friday!!!',food:4, water:6, hours_of_sleep:7, bowel_movement:1, friends:5, family:5)

t22 = Timesheet.create(user_id: caroline.id, date:'2018-12-01', text:'Hungout with friends!', food:3, water:6, hours_of_sleep:7, bowel_movement:1, friends:3, family:1 )
t12 = Timesheet.create(user_id: caroline.id, date:'2018-12-02', text:'Went to church.', food:3, water:7, hours_of_sleep:6, bowel_movement:0, friends:4, family:7)
t13 = Timesheet.create(user_id: caroline.id, date:'2018-12-03', text:'Did not get to finish the amount of work I wanted to get done.', food:2, water:0, hours_of_sleep:5, bowel_movement:1, friends:0, family:1)
t14 = Timesheet.create(user_id: caroline.id, date:'2018-12-05', text:'Work finished.', food:1, water:3, hours_of_sleep:1, bowel_movement:1, friends:0, family:1)
t15 = Timesheet.create(user_id: caroline.id, date:'2018-12-04', text:'Just worked all day.',food:2, water:2, hours_of_sleep:6, bowel_movement:1, friends:0, family:1)
t16 = Timesheet.create(user_id: caroline.id, date:'2018-12-09', text:'Didnt go to church.',food:3, water:2, hours_of_sleep:7, bowel_movement:1, friends:2, family:2)
t17 = Timesheet.create(user_id: caroline.id, date:'2018-12-07', text:'Was at school the whole day.',food:0, water:1, hours_of_sleep:5, bowel_movement:1, friends:0, family:1)
t18 = Timesheet.create(user_id: caroline.id, date:'2018-12-08', text:'Another day at school.',food:1, water:2, hours_of_sleep:4, bowel_movement:1, friends:0, family:0)
t19 = Timesheet.create(user_id: caroline.id, date:'2018-12-06', text:'Another day at school.',food:0, water:2, hours_of_sleep:3, bowel_movement:1, friends:0, family:0)
t20 = Timesheet.create(user_id: caroline.id, date:'2018-12-10', text:'Another day at school.',food:1, water:2, hours_of_sleep:4, bowel_movement:1, friends:0, family:0)
t21 = Timesheet.create(user_id: caroline.id, date:'2018-12-11', text:'Worked',food:4, water:3, hours_of_sleep:7, bowel_movement:1, friends:5, family:5)


tee1 = Timesheetemotion.create(timesheet_id: 6, emotion_id: 8)
tee2 = Timesheetemotion.create(timesheet_id: 6, emotion_id: 9)
tee3 = Timesheetemotion.create(timesheet_id: 6, emotion_id: 10)
tee4 = Timesheetemotion.create(timesheet_id: 7, emotion_id: 6)
tee5 = Timesheetemotion.create(timesheet_id: 7, emotion_id: 2)
tee6 = Timesheetemotion.create(timesheet_id: 7, emotion_id: 3)
tee7 = Timesheetemotion.create(timesheet_id: 8, emotion_id: 6)
tee8 = Timesheetemotion.create(timesheet_id: 9, emotion_id: 5)
tee9 = Timesheetemotion.create(timesheet_id: 9, emotion_id: 4)
tee10 = Timesheetemotion.create(timesheet_id: 10, emotion_id: 4)
tee11 = Timesheetemotion.create(timesheet_id: 10, emotion_id: 2)
tee12 = Timesheetemotion.create(timesheet_id: 11, emotion_id: 10)
tee13 = Timesheetemotion.create(timesheet_id: 22, emotion_id: 8)
tee20 = Timesheetemotion.create(timesheet_id: 22, emotion_id: 9)
tee21 = Timesheetemotion.create(timesheet_id: 12, emotion_id: 7)
tee14 = Timesheetemotion.create(timesheet_id: 13, emotion_id: 3)
tee15 = Timesheetemotion.create(timesheet_id: 13, emotion_id: 2)
tee16 = Timesheetemotion.create(timesheet_id: 14, emotion_id: 9)
tee17 = Timesheetemotion.create(timesheet_id: 15, emotion_id: 6)
tee18 = Timesheetemotion.create(timesheet_id: 15, emotion_id: 7)
tee19 = Timesheetemotion.create(timesheet_id: 16, emotion_id: 4)
tee22 = Timesheetemotion.create(timesheet_id: 17, emotion_id: 2)
tee23 = Timesheetemotion.create(timesheet_id: 18, emotion_id: 6)
tee24 = Timesheetemotion.create(timesheet_id: 19, emotion_id: 6)
tee25 = Timesheetemotion.create(timesheet_id: 20, emotion_id: 6)
tee26 = Timesheetemotion.create(timesheet_id: 21, emotion_id: 6)
   te1 = Timesheetemotion.create(timesheet_id: 1, emotion_id: 3)
   te2 = Timesheetemotion.create(timesheet_id: 1, emotion_id: 2)
   te3 = Timesheetemotion.create(timesheet_id: 1, emotion_id: 3)
   te4 = Timesheetemotion.create(timesheet_id: 2, emotion_id: 1)
   te5 = Timesheetemotion.create(timesheet_id: 2, emotion_id: 2)
   te6 = Timesheetemotion.create(timesheet_id: 2, emotion_id: 4)
   te7 = Timesheetemotion.create(timesheet_id: 3, emotion_id: 1)
   te8 = Timesheetemotion.create(timesheet_id: 3, emotion_id: 2)
   te9 = Timesheetemotion.create(timesheet_id: 3, emotion_id: 3)
   te10 = Timesheetemotion.create(timesheet_id: 4, emotion_id: 10)
   te11 = Timesheetemotion.create(timesheet_id: 5, emotion_id: 6)
   te12 = Timesheetemotion.create(timesheet_id: 5, emotion_id: 5)
